library(ape)
library(TreeDist)
generatingTree = read.tree("generatingTree.txt")
tree1 = read.tree("output1tr.txt")
tree2 = read.tree("output2tr.txt")
tree3 = read.tree("output3tr.txt")
tree4 = read.tree("output4tr.txt")
tree5 = read.tree("output5tr.txt")
td1 = TreeDistance(generatingTree, tree1)
td2 = TreeDistance(generatingTree, tree2)
td3 = TreeDistance(generatingTree, tree3)
td4 = TreeDistance(generatingTree, tree4)
td5 = TreeDistance(generatingTree, tree5)
print(td1)
print(td2)
print(td3)
print(td4)
print(td5)
txt <- c(as.character(td1), as.character(td2), as.character(td3), as.character(td4), as.character(td5))
writeLines(txt, "tree_distances.txt")